### ISSUE TITLE
New feature to set custom arrow submenu icon

### ISSUE THREAD

**Issue by inovramadani** [fkhadra/react-contexify#128]
Right now we have something like this for submenu:
![image](https://user-images.githubusercontent.com/27492820/65202547-a644b580-dab4-11e9-9acc-faab37169380.png)

I think it's nice if user can specify custom arrow for submenu through props.

**Comment by dpren** [comment]
Can't you just override the CSS?

```css
.react-contexify__submenu-arrow {
    color: transparent !important;
}
.react-contexify__submenu-arrow:after {
    content: "👉";
    color: black;
}
```

**Comment by tijmenvangurp** [comment]
@dpren Although your solution works, it does not feel like a good solution
![image](https://user-images.githubusercontent.com/9990026/88937810-e5bb6100-d284-11ea-8578-ebd4cbe8777a.png)
Setting the color to transparent still moves the next icon

If the arrow implementation for sub menu can change to use `content :"▶"` then the layout properties would remain correct.

**Comment by dpren** [comment]
@tijmenvangurp You're right, it's a hack. I don't mean to argue against first class support.

But note `.react-contexify__submenu-arrow` is absolutely positioned right, so the ::after icon actually pushes the original to the left. So there should be no visible layout difference, right?

Otherwise, you can hide it with font-size:

```css
.react-contexify__submenu-arrow {
    font-size: 0px;
}
.react-contexify__submenu-arrow::after {
    content: "👉";
    font-size: initial;
}
```
