### ISSUE TITLE
Submenu position

### ISSUE THREAD

**Issue by tijmenvangurp** [fkhadra/react-contexify#146]
It might be my ignorance of not know how to set this. 

I think this might be UI improvement

current situation:
![image](https://user-images.githubusercontent.com/9990026/88931574-4cd51780-d27d-11ea-9197-7774ff02d5d1.png)
The submenu does not allign
`top: 0px;`

Requested:
![image](https://user-images.githubusercontent.com/9990026/88931708-78580200-d27d-11ea-9af6-41af00b67df1.png)

Submenu item is aligned with the item in main menu
`top: 4px;`

How can I change this?

**Comment by tijmenvangurp** [comment]
I was able to fix it by overwriting the css

```css
.react-contexify .react-contexify__submenu{
    top: 4px!important;
}
```
