### ISSUE TITLE
how to change the style of this menu?!

### ISSUE THREAD

**Issue by Gelloiss** [fkhadra/react-contexify#258]
How to get rid of this blue background of the highlighted menu item? I tried to take all the css selectors from your documentation, by the way, there is an error in them, in the doc .contexify__item, but in fact .contexify_item. I tried to specify Item className, it works, but for hover or focus there is still a blue background, it is not replaced in any way!!!

**Comment by jooyeal** [comment]
I had a same issue
In my case, I could handle the style like below. I just overrode the style from parent element.

```css
.parent .contexify_itemContent,
.parent .contexify_itemContent:hover,
.parent .contexify_itemContent:focus {
     background-color: red !important;
}
```

I hope this method is helpful for you. even though quite some time has passed.
